name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate dataset with Pandera
        run: |
          python - <<'EOF'
          import pandas as pd
          from scripts.data.validate_data import validate_credit_data
          from scripts.data.prepare_data import prepare_data_df

          df = pd.read_csv('data/raw/UCI_Credit_Card.csv')
          df = prepare_data_df(df)
          
          try:
              validate_credit_data(df)
              print("Тесты пройдены")
          except Exception as e:
              print("Ошибка!")
              print(e)
              exit(1)
          EOF

      - name: Run Pytest
        run: pytest -v --maxfail=1 --disable-warnings

      - name: Run code style checks
        run: |
          pip install flake8 black
          flake8 src tests
          black --check src tests

      - name: Train and log models to MLflow
        run: |
          echo "Starting model training and MLflow logging..."
          python scripts/models/train_model.py

      - name: Upload trained models
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: models/